SELECT 
    COUNT(start_lat) AS count_start_lat,
    COUNT(start_lng) AS count_start_lng,
    COUNT(end_lat) AS count_end_lat,
    COUNT(end_lng) AS count_end_lng,
    AVG(start_lat) AS avg_start_lat,
    AVG(start_lng) AS avg_start_lng,
    AVG(end_lat) AS avg_end_lat,
    AVG(end_lng) AS avg_end_lng,
    STDDEV(start_lat) AS stddev_start_lat,
    STDDEV(start_lng) AS stddev_start_lng,
    STDDEV(end_lat) AS stddev_end_lat,
    STDDEV(end_lng) AS stddev_end_lng,
    MIN(start_lat) AS min_start_lat,
    MIN(start_lng) AS min_start_lng,
    MIN(end_lat) AS min_end_lat,
    MIN(end_lng) AS min_end_lng,
    MAX(start_lat) AS max_start_lat,
    MAX(start_lng) AS max_start_lng,
    MAX(end_lat) AS max_end_lat,
    MAX(end_lng) AS max_end_lng,
FROM `inner-nuance-436720-u7.last_12_months_trip_data1.tripdata_202406`